[versions]
axion = "1.21.1"
dockcross = "0.4.2"
mavenCentralPublish = "0.9.0"
jdtAnnotations = "2.4.0"
slf4j = "2.0.17"
logback = "1.3.15"
junitJupiter = "6.0.1"
jniAccessGenerator = "1.2.2"

[libraries]
jdtAnnotations = { module = "org.eclipse.jdt:org.eclipse.jdt.annotation", version.ref = "jdtAnnotations" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logbackClassic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiter" }
jniAccessGenerator = { module = "tel.schich:jni-access-generator", version.ref = "jniAccessGenerator" }

[plugins]
axion = { id = "pl.allegro.tech.build.axion-release", version.ref = "axion" }
dockcross = { id = "tel.schich.dockcross", version.ref = "dockcross" }
mavenCentralPublish = { id = "io.github.zenhelix.maven-central-publish", version.ref = "mavenCentralPublish" }
